version: "3"
services:
  cervo-api:
    build:
      context: ./
      dockerfile: Dockerfile-backend
    environment:
      #- PGHOST=
      #- PGUSER=
      #- PGDATABASE=
      #- PGPASSWORD=
      - PGPORT=5432
    ports:
      - "3000:3000"

  cervo-ui:
    build:
      context: ./
      dockerfile: Dockerfile-frontend
    ports:
      - "3001:1234"